// <auto-generated />
namespace Store_demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CheckHowAutoMapperWorks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CheckHowAutoMapperWorks));
        
        string IMigrationMetadata.Id
        {
            get { return "202104181148208_CheckHowAutoMapperWorks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
